/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessions actives */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: unknown[];
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Service auth indisponible */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Toutes les sessions révoquées */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Service auth indisponible */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Token de session */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Révoquée */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Service auth indisponible */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des clients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID */
                                id: string;
                                /** @description Nom du client */
                                nom: string;
                                /**
                                 * @description Type de client
                                 * @enum {string}
                                 */
                                type: "IMPORTATEUR" | "EXPORTATEUR" | "LES_DEUX";
                                /** @description Registre de commerce */
                                rc: string | null;
                                /** @description Numéro d'identification fiscale */
                                nif: string | null;
                                /** @description Contact */
                                contact: string | null;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Nom du client */
                        nom: string;
                        /**
                         * @description Type de client
                         * @enum {string}
                         */
                        type: "IMPORTATEUR" | "EXPORTATEUR" | "LES_DEUX";
                        /** @description Registre de commerce */
                        rc?: string;
                        /** @description Numéro d'identification fiscale */
                        nif?: string;
                        /** @description Contact */
                        contact?: string;
                    };
                };
            };
            responses: {
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID */
                                id: string;
                                /** @description Nom du client */
                                nom: string;
                                /**
                                 * @description Type de client
                                 * @enum {string}
                                 */
                                type: "IMPORTATEUR" | "EXPORTATEUR" | "LES_DEUX";
                                /** @description Registre de commerce */
                                rc: string | null;
                                /** @description Numéro d'identification fiscale */
                                nif: string | null;
                                /** @description Contact */
                                contact: string | null;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du client */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID */
                                id: string;
                                /** @description Nom du client */
                                nom: string;
                                /**
                                 * @description Type de client
                                 * @enum {string}
                                 */
                                type: "IMPORTATEUR" | "EXPORTATEUR" | "LES_DEUX";
                                /** @description Registre de commerce */
                                rc: string | null;
                                /** @description Numéro d'identification fiscale */
                                nif: string | null;
                                /** @description Contact */
                                contact: string | null;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du client */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du client */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Nom du client */
                        nom?: string;
                        /**
                         * @description Type de client
                         * @enum {string}
                         */
                        type?: "IMPORTATEUR" | "EXPORTATEUR" | "LES_DEUX";
                        /** @description Registre de commerce */
                        rc?: string;
                        /** @description Numéro d'identification fiscale */
                        nif?: string;
                        /** @description Contact */
                        contact?: string;
                    };
                };
            };
            responses: {
                /** @description Mis à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID */
                                id: string;
                                /** @description Nom du client */
                                nom: string;
                                /**
                                 * @description Type de client
                                 * @enum {string}
                                 */
                                type: "IMPORTATEUR" | "EXPORTATEUR" | "LES_DEUX";
                                /** @description Registre de commerce */
                                rc: string | null;
                                /** @description Numéro d'identification fiscale */
                                nif: string | null;
                                /** @description Contact */
                                contact: string | null;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/dossiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des dossiers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du dossier */
                                id: string;
                                /** @description Référence générée (ex: IMP-2025-0001) */
                                reference: string;
                                /**
                                 * @description Type de dossier
                                 * @enum {string}
                                 */
                                type: "IMPORT" | "EXPORT" | "TRANSIT" | "ADMISSION_TEMPORAIRE";
                                /**
                                 * @description Statut courant
                                 * @enum {string}
                                 */
                                statut: "BROUILLON" | "DEPOSE" | "EN_COURS" | "EN_ATTENTE" | "DEDOUANE" | "CLOTURE" | "REJETE";
                                /** @description UUID du régime douanier */
                                regimeId: string;
                                /** @description UUID du client */
                                clientId: string;
                                /** @description UUID de l'agent responsable */
                                agentId: string;
                                /** @description UUID du service */
                                serviceId: string;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Type de dossier douanier
                         * @enum {string}
                         */
                        type: "IMPORT" | "EXPORT" | "TRANSIT" | "ADMISSION_TEMPORAIRE";
                        /**
                         * Format: uuid
                         * @description UUID du régime douanier
                         */
                        regimeId: string;
                        /**
                         * Format: uuid
                         * @description UUID du client
                         */
                        clientId: string;
                        /**
                         * Format: uuid
                         * @description UUID du service
                         */
                        serviceId: string;
                    };
                };
            };
            responses: {
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du dossier */
                                id: string;
                                /** @description Référence générée (ex: IMP-2025-0001) */
                                reference: string;
                                /**
                                 * @description Type de dossier
                                 * @enum {string}
                                 */
                                type: "IMPORT" | "EXPORT" | "TRANSIT" | "ADMISSION_TEMPORAIRE";
                                /**
                                 * @description Statut courant
                                 * @enum {string}
                                 */
                                statut: "BROUILLON" | "DEPOSE" | "EN_COURS" | "EN_ATTENTE" | "DEDOUANE" | "CLOTURE" | "REJETE";
                                /** @description UUID du régime douanier */
                                regimeId: string;
                                /** @description UUID du client */
                                clientId: string;
                                /** @description UUID de l'agent responsable */
                                agentId: string;
                                /** @description UUID du service */
                                serviceId: string;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Erreur interne */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du dossier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dossier */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du dossier */
                                id: string;
                                /** @description Référence générée (ex: IMP-2025-0001) */
                                reference: string;
                                /**
                                 * @description Type de dossier
                                 * @enum {string}
                                 */
                                type: "IMPORT" | "EXPORT" | "TRANSIT" | "ADMISSION_TEMPORAIRE";
                                /**
                                 * @description Statut courant
                                 * @enum {string}
                                 */
                                statut: "BROUILLON" | "DEPOSE" | "EN_COURS" | "EN_ATTENTE" | "DEDOUANE" | "CLOTURE" | "REJETE";
                                /** @description UUID du régime douanier */
                                regimeId: string;
                                /** @description UUID du client */
                                clientId: string;
                                /** @description UUID de l'agent responsable */
                                agentId: string;
                                /** @description UUID du service */
                                serviceId: string;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du document */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Document introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{id}/statut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du dossier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Nouveau statut du dossier
                         * @enum {string}
                         */
                        statut: "BROUILLON" | "DEPOSE" | "EN_COURS" | "EN_ATTENTE" | "DEDOUANE" | "CLOTURE" | "REJETE";
                    };
                };
            };
            responses: {
                /** @description Statut mis à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du dossier */
                                id: string;
                                /** @description Référence générée (ex: IMP-2025-0001) */
                                reference: string;
                                /**
                                 * @description Type de dossier
                                 * @enum {string}
                                 */
                                type: "IMPORT" | "EXPORT" | "TRANSIT" | "ADMISSION_TEMPORAIRE";
                                /**
                                 * @description Statut courant
                                 * @enum {string}
                                 */
                                statut: "BROUILLON" | "DEPOSE" | "EN_COURS" | "EN_ATTENTE" | "DEDOUANE" | "CLOTURE" | "REJETE";
                                /** @description UUID du régime douanier */
                                regimeId: string;
                                /** @description UUID du client */
                                clientId: string;
                                /** @description UUID de l'agent responsable */
                                agentId: string;
                                /** @description UUID du service */
                                serviceId: string;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Transition invalide */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/dossiers/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du dossier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description UUID de l'agent à assigner
                         */
                        agentId: string;
                    };
                };
            };
            responses: {
                /** @description Agent assigné */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du dossier */
                                id: string;
                                /** @description Référence générée (ex: IMP-2025-0001) */
                                reference: string;
                                /**
                                 * @description Type de dossier
                                 * @enum {string}
                                 */
                                type: "IMPORT" | "EXPORT" | "TRANSIT" | "ADMISSION_TEMPORAIRE";
                                /**
                                 * @description Statut courant
                                 * @enum {string}
                                 */
                                statut: "BROUILLON" | "DEPOSE" | "EN_COURS" | "EN_ATTENTE" | "DEDOUANE" | "CLOTURE" | "REJETE";
                                /** @description UUID du régime douanier */
                                regimeId: string;
                                /** @description UUID du client */
                                clientId: string;
                                /** @description UUID de l'agent responsable */
                                agentId: string;
                                /** @description UUID du service */
                                serviceId: string;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                                /** @description Date de modification ISO 8601 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/dossiers/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du dossier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historique d'audit du dossier */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID de l'entrée d'audit */
                                id: string;
                                /** @description Type d'entité */
                                entityType: string;
                                /** @description UUID de l'entité */
                                entityId: string | null;
                                /** @description Action effectuée */
                                action: string;
                                /** @description UUID de l'utilisateur */
                                userId: string | null;
                                /** @description Données de l'action */
                                payload?: unknown;
                                /** @description Adresse IP */
                                ip: string | null;
                                /** @description User-Agent */
                                userAgent: string | null;
                                /** @description Date de création ISO 8601 */
                                createdAt: string;
                            }[];
                            meta: {
                                total: number;
                            };
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{dossierId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du dossier */
                    dossierId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Fichier à uploader
                         */
                        file?: string;
                        /**
                         * @description Type de document
                         * @enum {string}
                         */
                        typeDoc: "FACTURE" | "CONNAISSEMENT" | "CERTIFICAT_ORIGINE" | "LISTE_COLISAGE" | "DECLARATION" | "LICENCE" | "BON_COMMANDE" | "AUTRE";
                    };
                };
            };
            responses: {
                /** @description Document uploadé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du document */
                                id: string;
                                /** @description UUID du dossier parent */
                                dossierId: string;
                                /** @description Nom du fichier */
                                nom: string;
                                /**
                                 * @description Type de document
                                 * @enum {string}
                                 */
                                typeDoc: "FACTURE" | "CONNAISSEMENT" | "CERTIFICAT_ORIGINE" | "LISTE_COLISAGE" | "DECLARATION" | "LICENCE" | "BON_COMMANDE" | "AUTRE";
                                /** @description Clé de stockage S3 */
                                storageKey: string;
                                /** @description Taille en octets */
                                taille: number;
                                /** @description UUID de l'utilisateur ayant uploadé le document */
                                uploadedBy: string;
                                /** @description Date d'upload ISO 8601 */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Dossier introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du document */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description URL signée pour le téléchargement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description URL de téléchargement signée */
                                url: string;
                                /** @description Durée de validité en secondes */
                                expiresIn: number;
                            };
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Document introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{dossierId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du dossier */
                    dossierId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Fichier à uploader
                         */
                        file?: string;
                        /**
                         * @description Type de document
                         * @enum {string}
                         */
                        typeDoc: "FACTURE" | "CONNAISSEMENT" | "CERTIFICAT_ORIGINE" | "LISTE_COLISAGE" | "DECLARATION" | "LICENCE" | "BON_COMMANDE" | "AUTRE";
                    };
                };
            };
            responses: {
                /** @description Document uploadé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description UUID du document */
                                id: string;
                                /** @description UUID du dossier parent */
                                dossierId: string;
                                /** @description Nom du fichier */
                                nom: string;
                                /**
                                 * @description Type de document
                                 * @enum {string}
                                 */
                                typeDoc: "FACTURE" | "CONNAISSEMENT" | "CERTIFICAT_ORIGINE" | "LISTE_COLISAGE" | "DECLARATION" | "LICENCE" | "BON_COMMANDE" | "AUTRE";
                                /** @description Clé de stockage S3 */
                                storageKey: string;
                                /** @description Taille en octets */
                                taille: number;
                                /** @description UUID de l'utilisateur ayant uploadé le document */
                                uploadedBy: string;
                                /** @description Date d'upload ISO 8601 */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Dossier introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du document */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description URL signée pour le téléchargement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description URL de téléchargement signée */
                                url: string;
                                /** @description Durée de validité en secondes */
                                expiresIn: number;
                            };
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Document introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID du document */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Document introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
